/*!
 * hAzzle.js
 * Copyright (c) 2014 Kenny Flashlight
 * Version: 1.0.2a
 * Released under the MIT License.
 *
 * Date: 2014-11-14
 */
 
(function(){var h={},d={},g=function(a,c,b){if(a)throw Error("[hAzzle-"+c+"] "+b);},m=function(a){if(a&&"string"===typeof a)return h[a.toLowerCase()]},n=function(a){return a&&(a.ELEMENT_NODE||a.DOCUMENT_NODE)},e=function(a,c){if(a){if(!(this instanceof e))return new e(a,c);if(a instanceof e)return a;var b;b=m("Util");"function"===typeof a&&(d.ready?m("ready").ready(a):g(!0,6,"ready.js module not installed"));b="string"===typeof a?d.manipulation&&"<"===a[0]&&">"===a[a.length-1]&&3<=a.length?m("manipulation").create(a,
c&&c.nodeType?c.ownerDocument||c:document):this.find(a,c,!0):Array.isArray(a)?b.unique(b.filter(a,n)):this.isNodeList(a)?b.filter(b.makeArray(a),n):a.nodeType?11===a.nodeType?a.children:[a]:a===window?[a]:[];void 0===b?(this.length=0,this.elements=[]):(this.elements=b,this.length=b.length);return this}};e.err=g;e.installed=d;e.require=m;e.define=function(a,c){"string"!==typeof a||"function"!==typeof c||h[a]||(d[a.toLowerCase()]=!0,h[a.toLowerCase()]=c.call(e.prototype))};e.codename="new-age";e.version=
"1.0.1b";window.hAzzle=e})(window);var hAzzle=window.hAzzle||(window.hAzzle={});
hAzzle.define("has",function(){var h=navigator.userAgent,d=window,g=d.document,m=g.createElement("div"),n=Object.prototype.toString,e={},a=function(){if(g.documentMode)return g.documentMode;for(var a=7,c;4<a;a--)if(c=g.createElement("div"),c.innerHTML="\x3c!--[if IE "+a+"]><span></span><![endif]--\x3e",c.getElementsByTagName("span").length)return a}(),c=function(a){return"function"===typeof e[a]?e[a]=e[a](d,g,m):e[a]},b=function(a,b,k,q){("undefined"===typeof e[a]||q)&&(e[a]=b);return k&&c(a)};b("multiArgs",
function(){var a=document.createElement("div");a.classList.add("a","b");return/(^| )a( |$)/.test(a.className)&&/(^| )b( |$)/.test(a.className)});b("mobile",/^Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(h));b("android",/^Android/i.test(h));b("opera","[object Opera]"===n.call(window.opera));b("firefox","undefined"!==typeof InstallTrigger);b("chrome",d.chrome);b("webkit","WebkitAppearance"in g.documentElement.style);b("safari",0<n.call(window.HTMLElement).indexOf("Constructor"));
b("ie",function(){return!!g.documentMode});b("classlist",!!document.documentElement.classList);return{has:c,add:b,load:function(a,c,b){a?c([a],b):b()},cache:e,clear:function(a){a.innerHTML="";return a},ie:a}});
hAzzle.define("Types",function(){var h=Object.prototype.toString,d=Array.isArray,g=function(a){return"string"===typeof a},m=function(a){return"number"===typeof a},n=function(a){return a&&a.window===a},e=function(a){return a?function(b){return h.call(b)==="[object "+a+"]"}:function(){}},a=function(a){var b=Object.prototype.toString.call(a);if("[object HTMLCollection]"===b||"[object NodeList]"===b)return!0;if(!("length"in a&&"item"in a))return!1;try{if(null===a(0)||a(0)&&a(0).tagName)return!0}catch(d){}return!1};
this.isNodeList=a;return{isType:e,isArray:d,isEmpty:function(a){if(null==a)return!0;if(d(a)||g(a)||e("Arguments")(a))return 0===a.length;for(var b in a)if(null!=a&&Object.prototype.hasOwnProperty.call(a,b))return!1;return!0},isWindow:n,isObject:function(a){return null!==a&&"object"===typeof a},isPlainObject:function(a){return e("Object")(a)&&!n(a)&&Object.getPrototypeOf(a)==Object.prototype},isEmptyObject:function(a){for(var b in a)return!1;return!0},isNode:function(a){return!!a&&"object"===typeof a&&
"nodeType"in a},isElement:function(a){return!(!a||!a.nodeName)},isString:g,isArrayLike:function(a){if(null==a||n(a))return!1;var b=a.length;return 1===a.nodeType&&b?!0:g(a)||d(a)||0===b||"number"===typeof b&&0<b&&b-1 in a},isNumber:m,isBoolean:function(a){return"boolean"===typeof a},isNaN:function(a){return m(a)&&a!=+a},isDefined:function(a){return"undefined"!==typeof a},isUndefined:function(a){return"undefined"===typeof a},isNodeList:a}});
hAzzle.define("text",function(){var h=function(d){var g,m="",n=0;g=d.nodeType;if(!g)for(;g=d[n++];)m+=h(g);else if(1===g||9===g||11===g){if("string"===typeof d.textContent)return d.textContent;for(d=d.firstChild;d;d=d.nextSibling)m+=h(d)}else if(3===g||4===g)return d.nodeValue;return m};return{getText:h}});
hAzzle.define("util",function(){var h=Array.prototype.slice,d=hAzzle.require("types"),g=Object.keys,m=function(a,f){return Object.prototype.hasOwnProperty.call(a,f)},n=function(a,f,b,t){if(void 0===a)return a;hAzzle.err("function"!==typeof f,5,"'fn' must be a function in util.each()");var c,k=a.length,l;if("function"===typeof f&&"undefined"===typeof b&&"undefined"===typeof t&&d.isArray(a))for(;++c<k&&(c=t?a.length-c-1:c,!1!==f.call(a[c],a[c],c,a)););if(k===+k)for(c=0;c<k&&(c=t?a.length-c-1:c,!1!==
f.call(a[c],a[c],c,a));c++);else if(a)for(l in a)if(!1===f.call(a[l],a[l],l,a))break;return a},e=function(a,f,b){if("function"===typeof a){if(void 0===f)return a;b=b?b:3;return 1===b?function(b){return a.call(f,b)}:2===b?function(b,c){return a.call(f,b,c)}:3===b?function(b,c,s){return a.call(f,b,c,s)}:4===b?function(b,c,s,l){return a.call(f,b,c,s,l)}:function(){return a.apply(f,arguments)}}if(!a)return c},a=function(a,f,s){return a?"function"===typeof a?e(a,f,s):d.isObject(a)?b(a):p(a):c},c=function(a){return a},
b=function(a){var f=u(a),b=f.length;return function(a){if(!a)return!b;a=Object(a);for(var q=0,c,l;q<b;q++)if(c=f[q],l=c[0],c[1]!==a[l]||!(l in a))return!1;return!0}},u=function(a){for(var f=g(a),b=f.length,c=Array(b),k=0;k<b;k++)c[k]=[f[k],a[f[k]]];return c},p=function(a){return function(f){return f[a]}},k=function(b,f,c){if(null==b)return-1;var k=0,d=b.length;if(c)if("number"===typeof c)k=0>c?Math.max(0,d+c):c;else{c=a(void 0,void 0,1);for(var k=c(f),d=0,g=b.length;d<g;){var l=d+g>>>1;c(b[l])<k?
d=l+1:g=l}k=d;return b[k]===f?k:-1}for(;k<d;k++)if(b[k]===f)return k;return-1};return{map:function(b,f,c){if(b){f=a(f,c);c=b.length!==+b.length&&g(b);for(var k=(c||b).length,d=Array(k),e,l=0;l<k;l++)e=c?c[l]:l,d[l]=f.call(b[e],b[e],e,b);return d}return[]},some:function(b,f,c){if(b){f=a(f,c);c=(k||b).length;var k,d=0,e;for(b.length!==+b.length&&(k=k(b));d<c;d++)if(e=k?k[d]:d,f(b[e],e,b))return!0}return!1},reduce:function(a,b,c,k){a||(a=[]);b=e(b,k,4);var d=a.length!==+a.length&&g(a),h=(d||a).length,
l=0,w;3>arguments.length&&(hAzzle.err(!h,7," no collection length exist in collection.reduce()"),c=a[d?d[l++]:l++]);for(;l<h;l++)w=d?d[l]:l,c=b(c,a[w],w,a);return c},each:n,mixin:function(a){if(d.isObject(a))for(var b,c,k=1,e=arguments.length;k<e;k++)for(c in b=arguments[k],b)m(b,c)&&(a[c]=b[c]);return a},makeArray:function(a){if(d.isArray(a))return a;for(var b=-1,c=a.length,k=Array(c);++b<c;)k[b]=a[b];return k},merge:function(a,b){for(var c=+b.length,k=0,d=a.length;k<c;k++)a[d++]=b[k];a.length=d;
return a},nodeName:function(a,b){return a&&a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},unique:function(b,c,e,g){if(!b)return[];d.isBoolean(c)&&(g=e,e=c,c=!1);void 0!==e&&(e=a(e,g));g=[];for(var h=[],m=0,l,w=b.length;m<w;m++)if(l=b[m],c)m&&h===l||g.push(l),h=l;else if(e){var y=e(l,m,b);0>k(h,y)&&(h.push(y),g.push(l))}else 0>k(g,l)&&g.push(l);return g},indexOf:k,filter:function(b,c,k){var d=[];if(!b)return d;c=a(c,k);n(b,function(a,b,l){c(a,b,l)&&d.push(a)});return d},now:Date.now,has:m,
bind:function(a,b){var c=2<arguments.length?h.call(arguments,2):[],k;"string"===typeof b&&(k=a[b],b=a,a=k);return"function"!==typeof a||b instanceof RegExp?b:c.length?function(){return arguments.length?a.apply(b||this,c.concat(h.call(arguments,0))):a.apply(b||this,c)}:function(){return arguments.length?a.apply(b||this,arguments):a.call(b||this)}}}});
hAzzle.define("Core",function(){var h=1,d=window.document,g=window.document,m="hAzzle_"+1*new Date,n,e,a=Array.prototype.indexOf,c={},b,u=d.createElement("div").compareDocumentPosition(d.createElement("div"))&1,p,k=function(){return!!p},q=function(a,b){a===b&&(p=!0);return 0},f=m.split("").sort(q).join("")===m,s=function(a,b){var l=b&&a,c=l&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||-2147483648)-(~a.sourceIndex||-2147483648);if(c)return c;if(l)for(;l=l.nextSibling;)if(l===b)return-1;return a?
1:-1},t=function(a){return/^[^{]+\{\s*\[native \w/.test(""+a)},v=function(a){var b,l,k,f;n=a=a.ownerDocument||a;b=a.documentElement;if(9!==n.nodeType||!n.documentElement)return d;d=a;if(l=b.getAttribute("__hAzzle"))return e=c[l];b.setAttribute("__hAzzle",h);e={id:++h};e.qsa=t(a.querySelectorAll);e.compare=t(b.compareDocumentPosition);e.contains=t(b.contains);e.QSABugs=k=[];e.matchesBugs=f=[];e.qsa&&(l=a.createElement("div"),l.appendChild(a.createElement("select")),(a=a.createElement("option")).setAttribute("selected",
""),l.firstChild.appendChild(a),l.querySelectorAll(":checked").length||k.push(":checked"),e.QSABugs=k.length&&new RegExp(k.join("|")));t(b=b.webkitMatchesSelector||b.mozMatchesSelector||b.oMatchesSelector||b.msMatchesSelector)&&(e.matchesSelector=b,e.disconMatch=b.call(l,"div"),e.matchesBugs=f.length&&new RegExp(f.join("|")));c[h]=e;return c[h]};v(d);var r=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1},l=e.compare&&e.contains?function(a,b){var l=9===a.nodeType?
a.documentElement:a,c=b&&b.parentElement;return a===c||!!(c&&1===c.nodeType&&(l.contains?l.contains(c):a.compareDocumentPosition&&a.compareDocumentPosition(c)&16))}:function(a,b){if(b)for(;b=b.parentElement;)if(b===a)return!0;return!1},q=e.compare?function(c,k){if(c===k)return p=!0,0;var f=!c.compareDocumentPosition-!k.compareDocumentPosition;if(f)return f;f=(c.ownerDocument||c)===(k.ownerDocument||k)?c.compareDocumentPosition(k):1;return f&1||!u&&k.compareDocumentPosition(c)===f?c===n||c.ownerDocument===
g&&l(g,c)?-1:k===n||k.ownerDocument===g&&l(g,k)?1:b?a(b,c)-a(b,k):0:f&4?-1:1}:function(l,c){if(l===c)return p=!0,0;var k,f=0,d=l.parentNode,e=c.parentNode,h=[l],q=[c];if(!d||!e)return l===k?-1:c===k?1:d?-1:e?1:b?a(b,l)-a(b,c):0;if(d===e)return s(l,c);for(k=l;k=k.parentNode;)h.unshift(k);for(k=c;k=k.parentNode;)q.unshift(k);for(;h[f]===q[f];)f++;return f?s(h[f],q[f]):h[f]===g?-1:q[f]===g?1:0};return{environment:e,expando:m,addFeature:function(a,b){"string"===typeof a&&b&&(c[h][a]=b)},setDocument:v,
isXML:r,isHTML:!r(d),contains:l,unique:function(a){var l,c=[],d=0,e=0;p=!k;b=!f&&a.slice(0);a.sort(q);if(p){for(;l=a[e++];)l===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}b=null;return a},matches:e.matchesSelector,qsa:e.qsa,QSABugs:e.QSABugs,matchesBugs:e.matchesBugs}});
hAzzle.define("Collection",function(){var h=hAzzle.require("util"),d=hAzzle.require("types"),g=Array.prototype,m=g.concat,n=g.push,e=function(a,c,b){"undefined"===typeof c&&(c=0);"undefined"===typeof b&&(b=a?a.length:0);var d=-1;b=b-c||0;for(var e=Array(0>b?0:b);++d<b;)e[d]=a[c+d];return e};this.toJqueryZepto=function(){for(var a=this.length,c=this.elements;a--;)this[a]=c[a];return this};this.get=function(a){var c=this.elements;return void 0===a?e(c,0):0>a?c[this.length+a]:c[a]};this.eq=function(a){return hAzzle(-1===
a?e(this.elements,this.length-1):e(this.elements,a,a+1))};this.reduce=function(a,c,b){return h.reduce(this.elements,a,c,b)};this.indexOf=function(a,c,b){return null==c?-1:g.indexOf.call(c,a,b)};this.map=function(a,c){return hAzzle(h.map(this.elements,a,c))};this.each=function(a,c,b){h.each(this.elements,a,c,b);return this};this.slice=function(a,c){return hAzzle(e(this.elements,a,c))};this.concat=function(){var a=h.map(e(arguments),function(a){return a instanceof hAzzle?a.elements:a});return hAzzle(m.apply(this.elements,
a))};this.contents=function(){return this.map(function(){return this.contentDocument||e(this.childNodes)})};this.is=function(a){return 0<this.length&&0<this.filter(a).length};this.not=function(a){return this.filter(a,!0)};this.index=function(a){var c=this.elements;return a?"string"===typeof a?h.indexOf(hAzzle(a).elements,c[0]):h.indexOf(c,a instanceof hAzzle?a.elements[0]:a):c[0]&&c[0].parentElement?this.first().prevAll().length:-1};this.add=function(a,c){var b=a;"string"===typeof a&&(b=hAzzle(a,
c).elements);return this.concat(b)};this.first=function(a){return a?this.slice(0,a):this.eq(0)};this.last=function(a){return a?this.slice(this.length-a):this.eq(-1)};this.even=function(){return this.filter(function(a){return 0!==a%2})};this.odd=function(){return this.filter(function(a){return 0===a%2})};h.each({next:"nextElementSibling",prev:"previousElementSibling"},function(a,c){this[c]=function(b){return this.map(function(){return this[a]}).filter(b)}}.bind(this));h.each({prevAll:"previousElementSibling",
nextAll:"nextElementSibling"},function(a,c){this[c]=function(){var b=[];this.each(function(c){for(;(c=c[a])&&9!==c.nodeType;)b.push(c)});return hAzzle(b)}}.bind(this));return{makeArray:function(a,c){var b=c||[];void 0!==a&&(d.isArrayLike(Object(a))?h.merge(b,d.isString(a)?[a]:a):n.call(b,a));return b},inArray:function(a,c,b){return void 0===c?-1:g.indexOf.call(c,a,b)},slice:e,includes:function(a,c){return-1!=g.indexOf.call(a,c)},arrayRemove:function(a,c){var b=a.indexOf(c);0<=b&&a.splice(b,1);return c}}});
hAzzle.define("Jiesa",function(){var h=hAzzle.require("util"),d=hAzzle.require("core"),g=hAzzle.require("collection"),m=hAzzle.require("types"),n=hAzzle.require("has"),e=/^(?:#([\w-]+)|\.([\w-]+)|(\w+))$/,a=/^(\w+)(?:#([\w-]+)|)(?:\.([\w-]+)|)$/,c=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g,b=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,u=/^(\w*)(?:#([\w\-]+))?(?:\[([\w\-\=]+)\])?(?:\.([\w\-]+))?$/,p=/^\s*[+~]/,k=/[\n\t\r]/g,q={":enabled":function(a){return!1===a.disabled},":disabled":function(a){return!0===
a.disabled},":checked":function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},":hidden":function(a){var b=a.style;return!b||"none"!==b.display&&"hidden"!==b.visibility?"hidden"===a.type:!0},":visible":function(a){return!q[":hidden"](a)}},f=function(a,b,k){var f=a,d=a.getAttribute("id"),e=d||"__hAzzle__",g=a.parentNode,h=p.test(b);if(h&&!g)return[];d?e=e.replace(/'/g,"\\$&"):a.setAttribute("id",e);h&&g&&(a=a.parentNode);b=b.match(c);for(g=0;g<b.length;g++)b[g]=
"[id='"+e+"'] "+b[g];b=b.join(",");try{return k.call(a,b)}finally{d||f.removeAttribute("id")}},s=function(a,b,c){return c&&9!==c.nodeType?f(c,b,function(b){return a.matches(b)}):a.matches(b)},t=function(a){return a?"string"===typeof a?v(a):!a.nodeType&&m.isArrayLike(a)?a[0]:a:document},v=function(b,c){var q,x,m,p,s=[];c=t(c);if(!b||"string"!==typeof b)return s;if(1!==(x=c.nodeType)&&9!==x&&11!==x)return[];if(d.isHTML){if(q=e.exec(b)){if(b=q[1]){if(9===x)return(m=c.getElementById(b))&&m.id===b?[m]:
[];if(c.ownerDocument&&(m=c.ownerDocument.getElementById(b))&&d.contains(c,m)&&m.id===q)return[m]}else if(b=q[2])p=c.getElementsByClassName(b);else if(b=q[3])p=c.getElementsByTagName(b);return g.slice(p)}if(q=a.exec(b)){x=c.getElementsByTagName(q[1]);var u=q[2],r=q[3];h.each(x,function(a){var b;(b=a.id===u)||(b=n.has("classList")?a.classList.contains(r):0<=(" "+a.className+" ").replace(k," ").indexOf(r));b&&s.push(a)});return s}}if(d.qsa&&(!d.QSABugs||!d.QSABugs.test(b)))try{return p=1===c.nodeType?
f(c,b,c.querySelectorAll):c.querySelectorAll(b),g.slice(p)}catch(v){}},r=function(a,c,k){if(c.nodeType)return a===c;(a.ownerDocument||a)!==document&&d.setDocument(a);c="string"===typeof c?c.replace(b,"='$1']"):c;if(c instanceof hAzzle)return h.some(c.elements,function(b){return r(a,b)});if(a===document)return!1;var f=u.exec(c);if(f)return f[1]&&(f[1]=f[1].toLowerCase()),f[3]&&(f[3]=f[3].split("=")),f[4]&&(f[4]=" "+f[4]+" "),(!f[1]||a.nodeName.toLowerCase()===f[1])&&(!f[2]||a.id===f[2])&&(!f[3]||(f[3][1]?
a.getAttribute(f[3][0])===f[3][1]:a.hasAttribute(f[3][0])))&&(!f[4]||0<=(" "+a.className+" ").indexOf(f[4]));if(f=q[c])return!!f(a);if(!d.matches||!d.isHTML||d.rbuggyMatches&&d.rbuggyMatches.test(c)||d.QSABugs&&d.QSABugs.test(c))hAzzle.err(!0,23," jiesa.js module need to be installed");else try{var e=s(a,c,k);if(e||d.disconMatch||a.document&&11!==a.document.nodeType)return e}catch(g){}};this.find=function(a,b,c){if(!c){if("string"!==typeof a){var k=0,f=this.length,e=this.elements;return hAzzle(h.filter(hAzzle(a).elements,
function(a){for(;k<f;k++)if(d.contains(e[k],a))return!0}))}return h.reduce(this.elements,function(b,c){return hAzzle(b.concat(g.slice(v(a,c))))},[])}return v(a,b)};this.filter=function(a,b){if(void 0===a)return this;if("function"===typeof a){var c=[];this.each(function(b,k){a.call(b,k)&&c.push(b)});return hAzzle(c)}return this.filter(function(){return r(this,a)!==(b||!1)})};return{matchesSelector:s,matches:r,pseudos:q,find:v}});
hAzzle.define("Strings",function(){var h=/[A-Z]/g,d=/([\:\-\_]+(.))/g,g=/^moz([A-Z])/,m=[],n=function(a,c,b,d){return d?b.toUpperCase():b},e=function(a){return"-"+a.charAt(0).toLowerCase()};return{capitalize:function(a){return a&&"string"===typeof a?a.charAt(0).toUpperCase()+a.slice(1):""},unCapitalize:function(a){return a&&"string"===typeof a?a.charAt(0).toLowerCase()+a.slice(1):""},hyphenate:function(a){return"string"===typeof a?a?a.replace(h,e):a:(a="number"===typeof a?""+a:"")?"data-"+a.toLowerCase():
a},camelize:function(a){return m[a]?m[a]:m[a]=a.replace(d,n).replace(g,"Moz$1")},trim:function(a){return"string"===typeof a?a.trim():a},lowercase:function(a){return"string"===typeof a?a.toLowerCase():a},uppercase:function(a){return"string"===typeof a?a.toUpperCase():a}}});
hAzzle.define("storage",function(){function h(){this.expando=e.expando+Math.random()}function d(b,d,f){if(void 0===f&&1===b.nodeType)if(f="data-"+d.replace(c,"-$1").toLowerCase(),f=b.getAttribute(f),"string"===typeof f){try{f="true"===f?!0:"false"===f?!1:"null"===f?null:+f+""===f?+f:a.test(f)?JSON.parse(f+""):f}catch(e){}p.set(b,d,f)}else f=void 0;return f}var g=hAzzle.require("util"),m=hAzzle.require("strings"),n=hAzzle.require("types"),e=hAzzle.require("core"),a=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,
c=/([A-Z])/g,b=/\S+/g;h.accepts=function(a){if(a)return 1===a.nodeType||9===a.nodeType||!+a.nodeType};h.prototype={register:function(a,b){hAzzle.err(!n.isObject(a),22,"no valid DOM element in storage.js");var c={};c[this.expando]={value:b||{},writable:!0,configurable:!0};a.nodeType?a[this.expando]={value:b||{}}:Object.defineProperties(a,c);return a[this.expando]},cache:function(a,b){if(!h.accepts(a))return{};var c=a[this.expando];return c?c:this.register(a,b)},set:function(a,b,c){if(a){var d;if(a=
this.cache(a)){if("string"===typeof b)a[b]=c;else if(n.isEmptyObject(a))g.mixin(a,b);else for(d in b)a[d]=b[d];return a}}},access:function(a,b,c){if(void 0===b||b&&"string"===typeof b&&void 0===c)return c=this.get(a,b),void 0!==c?c:this.get(a,m.camelize(b));this.set(a,b,c);return void 0!==c?c:b},get:function(a,b){var c=this.cache(a);if(c)return void 0!==c&&void 0===b?c:c[b]},release:function(a,c){var f,d,e=this.cache(a);if(void 0===c)this.register(a);else for(n.isArray(c)?d=c.concat(c.map(m.camelize)):
(f=m.camelize(c),c in e?d=[c,f]:(d=f,d=e[d]?[d]:d.match(b)||[])),f=d.length;f--;)delete e[d[f]]},hasData:function(a){return!n.isEmptyObject(a[this.expando]||{})},flush:function(a){a[this.expando]&&delete a[this.expando]}};var u=new h,p=new h;this.data=function(a,b){var c,e,g,h=this.elements[0],n=h&&h.attributes;if(void 0===a){if(this.length&&(g=p.get(h),1===h.nodeType&&!u.get(h,"hasDataAttrs"))){for(c=n.length;c--;)n[c]&&(e=n[c].name,0===e.indexOf("data-")&&(e=m.camelize(e.slice(5)),d(h,e,g[e])));
u.set(h,"hasDataAttrs",!0)}return g}if("object"===typeof a)return this.each(function(b){p.set(b,a)});var l=m.camelize(a);if(h&&void 0===b){g=p.get(h,a);if(void 0!==g)return g;g=p.get(h,l);var w=u.get(this,"hasDataAttrs"),y=-1!==a.indexOf("-");if(void 0!==g)return g;g=d(h,l,void 0);if(void 0!==g)return g}else this.each(function(c){var d=p.get(c,l);p.set(c,l,b);y&&void 0!==d&&p.set(c,a,b);y&&void 0===w&&p.set(c,a,b)})};this.removeData=function(a){return this.each(function(b){p.release(b,a)})};return{"private":u,
data:p}});
hAzzle.define("css",function(){var h=hAzzle.require("storage"),d=hAzzle.require("has"),g="b big i small abbr acronym cite code dfn em kbd strong samp var a bdo br img mapobject q script span sub button input label select textarea".split(" "),m=/^(width|height)$/,n=/^(li)$/i,e=/^(tr)$/i,a=/^(table)$/i,c=/^margin/,b=/^#/,u=/^border(Top|Right|Bottom|Left)?$/,p=/^(.+)\s(.+)\s(.+)$/,k=/^([+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|))(?!px)[a-z%]+$/i,q=function(){var a=document.createElement("div");a.style.border="1px solid #123abc";
return"1px solid #123abc"!=a.style.border}(),f=function(a){if(a)return void 0===h["private"].get(a,"css")&&h["private"].access(a,"css",{computedStyle:null}),h["private"].get(a,"css")},s=function(a){var b;if(null===f(a).computedStyle){b=f(a);if(a&&null!==a.ownerDocument){var c=!1;a?(void 0!==a.ownerDocument&&(c=a.ownerDocument.defaultView),a=c&&c.opener?c.getComputedStyle(a,null):window.getComputedStyle(a,null)):a=a.style}else a="";b=b.computedStyle=a}else b=f(a).computedStyle;return b},t=function(a){return parseFloat(a)||
0},v=function(b){if(b){b=b.tagName.toLowerCase();if(b in g)return"inline";if(n.test(b))return"list-item";if(e.test(b))return"table-row";if(a.test(b))return"table"}return"block"},r=function(a,e,g){a=a instanceof hAzzle?a.elements[0]:a;var h=0;m.test(e)&&0===r(a,"display")&&(a.style.display="none",a.style.display=v(a));if(d.has("ie")&&"auto"===e){if("height"===e)return a.offsetHeight;if("width"===e)return a.offsetWidth}if(!g){if("height"===e&&"border-box"!==r(a,"boxSizing").toString().toLowerCase())return a.offsetHeight-
t(r(a,"borderTopWidth"))-t(r(a,"borderBottomWidth"))-t(r(a,"paddingTop"))-t(r(a,"paddingBottom"));if("width"===e&&"border-box"!==r(a,"boxSizing").toString().toLowerCase())return a.offsetWidth-t(r(a,"borderLeftWidth"))-t(r(a,"borderRightWidth"))-t(r(a,"paddingLeft"))-t(r(a,"paddingRight"))}if(g=s(a))if((d.ie||d.has("firefox"))&&"borderColor"===e&&(e="borderTopColor"),9===d.ie?(h="filter"===e?g.getPropertyValue(e):g[e],q&&u.test(e)&&b.test(h)&&h.replace(p,"$2 $3 $1")):h=g[e],""!==h||hAzzle.require("Core").contains(a.ownerDocument,
a)||(h=a.style[e]),d.has("mobile")&&d.has("android")&&k.test(h)&&c.test(name)){var n=a.style;a=n.width;e=n.minWidth;g=n.maxWidth;n.minWidth=n.maxWidth=n.width=h;h=f.width;n.width=a;n.minWidth=e;n.maxWidth=g}return void 0!==h?h+"":h};return{computed:f,display:v,styles:s,css:r}});
hAzzle.define("setters",function(){var h=hAzzle.require("util"),d=hAzzle.require("core"),g=hAzzle.require("types"),m=/\S+/g,n=/\r/g,e="multiple selected checked disabled readonly required async autofocus compact nowrap declare noshade hreflang onload srcnoresize defaultChecked autoplay controls defer autocomplete hidden tabindex readonly type accesskey dropzone spellcheck ismap loop scoped open".split(" "),a={},c={},b={"class":"className","for":"htmlFor"},u={get:{},set:{}},p={get:{},set:{}},k={get:{},
set:{}},q={get:{},set:{}},f={get:{},set:{}},s=function(a){return a instanceof hAzzle?a.elements:a},t=function(b,d){var e=a[d.toLowerCase()];return e&&c[b.nodeName]&&e},v=function(a,c){a=s(a);var d,e,f=0,g=c&&c.match(m);if(g&&1===a.nodeType)for(;d=g[f++];)e=b[d]||d,t(a,d)?a[e]=!1:a.removeAttribute(d),a.removeAttribute(d)},r=function(a,b,c){var e=(a=s(a))?a.nodeType:void 0,g,k;if(e&&(3!==e||8!==e||2!==e)){if("undefined"===typeof a.getAttribute)return l(a,b,c);1===e&&d.isXML(a)||(b=b.toLowerCase(),g=
p["undefined"===c?"get":"set"][b]||t(a,b)?f["undefined"===c?"get":"set"][b]:q["undefined"===c?"get":"set"][b]);if(void 0===c){if(g&&(k=g.get(a,b))&&null!==k)return k;k=a.getAttribute(b,2);return null==k?void 0:k}if(c){if(g&&void 0!==(k=g.set(a,c,b)))return k;a.setAttribute(b,c+"")}else v(a,b)}return""},l=function(a,c,e){var f=(a=s(a))?a.nodeType:void 0,g,k;if(f&&(3!==f||8!==f||2!==f)){if(1!==f||d.isHTML)c=b[c]||c,g="undefined"===e?u.get[c]:u.set[c];return"undefined"!==typeof e?g&&void 0!==(k=g.set(a,
e,c))?k:a[c]=e:g&&null!==(k=g(a,c))?k:a[c]}return""};this.val=function(a){var b,c,e;c=this.elements[0];if(arguments.length)return e=g.isType("Function")(a),this.each(function(c,d){var f;1===c.nodeType&&(f=e?a.call(c,d,hAzzle(c).val()):a,null==f?f="":"number"===typeof f?f+="":g.isArray(f)&&(f=h.map(f,function(a){return null==a?"":a+""})),b=k.set[c.type]||k.set[c.nodeName.toLowerCase()],b&&void 0!==b(c,f,"value")||(c.value=f))});if(c){if(b=k.get[c.type]||k.get[c.nodeName.toLowerCase()])return b(c,"value");
c=c.value;return"string"===typeof c?c.replace(n,""):null==c?"":c}};this.prop=function(a,b){var c=this.elements;if("object"===typeof a)return this.each(function(b){h.each(a,function(a,c){l(b,c,a)})});if("undefined"===typeof b)return l(c[0],a);this.each(c,function(c){l(c,a,b)})};this.toggleProp=function(a){return this.each(function(b){return b.prop(a,!b.prop(a))})};this.removeProp=function(a){return this.each(function(){delete this[b[a]||a]})};this.removeAttr=function(a){return this.each(function(b){v(b,
a)})};this.attr=function(a,b){var c=this.elements;return"object"===typeof a?this.each(function(b){h.each(a,function(a,c){r(b,c,a)})}):"undefined"===typeof b?r(c[0],a):this.each(function(c){r(c,a,b)})};h.each(e,function(b){a[e[b]]=e[b]});h.each("input select option textarea button form details".split(" "),function(a){c[a.toUpperCase()]=!0});h.each("cellPadding cellSpacing maxLength rowSpan colSpan useMap frameBorder contentEditable textContent valueType tabIndex readOnly type accessKey tabIndex dropZone spellCheck hrefLang isMap srcDoc mediaGroup autoComplete noValidate radioGroup".split(" "),
function(a){b[a.toLowerCase()]=a});return{attrHooks:p,propHooks:u,valHooks:k,boolHooks:f,nodeHooks:q,propMap:b,boolAttr:a,boolElem:c,removeAttr:v,attr:r,prop:l}});hAzzle.define("boolhooks",function(){var h=hAzzle.require("setters");h.boolHooks.set=function(d,g,m){!1===g?h.removeAttr(d,m):d.setAttribute(m,m);return m};return{}});
hAzzle.define("attrHooks",function(){var h=hAzzle.require("util"),d=hAzzle.require("setters"),g=function(){var d=document.createElement("input");d.type="checkbox";d=document.createElement("input");d.value="t";d.type="radio";return"t"===d.value}();h.mixin(d.attrHooks.set,{type:function(d,n){if(!g&&"radio"===n&&h.nodeName(d,"input")){var e=d.value;d.setAttribute("type",n);e&&(d.value=e);return n}}});return{}});
hAzzle.define("prophooks",function(){var h=hAzzle.require("util"),d=hAzzle.require("setters");h.mixin(d.propHooks.get,{tabIndex:function(d){return d.hasAttribute("tabindex")||/^(?:input|select|textarea|button)$/i.test(d.nodeName)||d.href?d.tabIndex:-1}});document.createElement("select").appendChild(document.createElement("option")).selected||(d.propHooks.get.selected=function(d){(d=d.parentNode)&&d.parentNode&&d.parentNode.selectedIndex;return null});return{}});
hAzzle.define("valHooks",function(){var h=hAzzle.require("util"),d=hAzzle.require("strings"),g=hAzzle.require("text"),m=hAzzle.require("types"),n=hAzzle.require("collection"),e=hAzzle.require("setters"),a=function(){var a=document.createElement("input");a.type="checkbox";a.checked=!0;a=a.getAttributeNode("checked");return!a||!a.specified}(),c=function(a,c,d){var e=a.length;for(d=0>d?Math.max(0,e+d):d||0;d<e;d++)if(a[d]===c)return d;return-1};h.mixin(e.valHooks.set,{select:function(a,d){for(var e,
k,g=a.options,f=n.makeArray(d),h=g.length;h--;)if(k=g[h],k.selected=0<=c(f,k.value))e=!0;e||(a.selectedIndex=-1);return f}});h.mixin(e.valHooks.get,{option:function(a){var c=a.getAttribute(name,2);return null!==c?c:d.trim(g.getText(a))},select:function(a){var c=a.selectedIndex,d="select-one"===a.type;a=a.options;var e=[],g,f,h;if(0>c)return"";h=d?c:0;for(f=d?c+1:a.length;h<f;h++)if(g=a[h],g.selected&&null===g.getAttribute("disabled")&&(!g.parentElement.disabled||"OPTGROUP"!==g.parentElement.tagName)){g=
hAzzle(g).val();if(d)return g;e.push(g)}return d&&!e.length&&a.length?a[c].value:e}});h.each(["radio","checkbox"],function(a){e.valHooks.set[a]=function(a,b){if(m.isArray(b))return a.checked=0<=c(b,hAzzle(a).val())}});a||(e.valHooks.get[val]=function(a){return null===a.getAttribute("value")?"on":a.value});return{}});
(function(h){function d(a){return"string"===typeof a?h.document.createTextNode(a):a}function g(a){var b=h.document.createDocumentFragment(),c=n.call(a,0),e=0,f=a.length;if(1===a.length)return d(a[0]);for(;e<f;e++)try{b.appendChild(d(c[e]))}catch(g){}return b}for(var m=Array.prototype,n=m.slice,e=m.indexOf,m=(h.Element||h.Node||h.HTMLElement).prototype,a=["append",function(){try{this.appendChild(g(arguments))}catch(a){}},"prepend",function(){try{this.firstChild?this.insertBefore(g(arguments),this.firstChild):
this.appendChild(g(arguments))}catch(a){}},"before",function(){var a=this.parentElement;a&&a.insertBefore(g(arguments),this)},"after",function(){this.parentElement&&(this.nextSibling?this.parentElement.insertBefore(g(arguments),this.nextSibling):this.parentElement.appendChild(g(arguments)))},"replace",function(){this.parentElement&&this.parentElement.replaceChild(g(arguments),this)},"remove",function(){this.parentElement&&this.parentElement.removeChild(this)},"matches",m.matchesSelector||m.webkitMatchesSelector||
m.mozMatchesSelector||m.msMatchesSelector||function(a){var b=this.parentElement;return!!b&&-1<e.call(b.querySelectorAll(a),this)}],c=a.length;c;c-=2)m[a[c-2]]||(m[a[c-2]]=a[c-1]);try{new h.CustomEvent("?")}catch(b){h.CustomEvent=function(a,b){function c(a,b,d,e){this.initEvent(a,b,d);this.detail=e}return function(d,e){var g=document.createEvent(a);if("string"!==typeof d)throw Error("An event name must be provided");"Event"===a&&(g.initCustomEvent=c);null==e&&(e=b);g.initCustomEvent(d,e.bubbles,e.cancelable,
e.detail);return g}}(h.CustomEvent?"CustomEvent":"Event",{bubbles:!1,cancelable:!1,detail:null})}})(window);