/*!
 * hAzzle.js
 * Copyright (c) 2014 Kenny Flashlight
 * Version: 1.0.1a
 * Released under the MIT License.
 *
 * Date: 2014-11-08
 */
(function(){var e=/^#([\w\-]*)$/,k={},f={},l=function(c,d,b){if(c)throw c=Error("[hAzzle-"+d+"] "+b),c.code=d,c;},q=function(c){return c&&(c.ELEMENT_NODE||c.DOCUMENT_NODE)},h=function(c,d){if(c){if(!(this instanceof h))return new h(c,d);if(c instanceof h)return c;var b,m,n=h.require("Util"),a=h.require("Ready");"function"===typeof c&&(f.Ready?a.ready(c):l(!0,6,"ready.js module not installed"));if("string"===typeof c){if((b=e.exec(c))&&!d&&(m=[document.getElementById(b[1])]),null===m||void 0===m)m=
this.find(c,d,!0)}else m=c instanceof Array?n.unique(n.filter(c,q)):this.isNodeList(c)?n.filter(n.makeArray(c),q):c.nodeType?11===c.nodeType?c.children:[c]:c===window?[c]:[];void 0===m?(this.length=0,this.elements=[]):(this.elements=m,this.length=m.length);return this}};h.err=l;h.installed=f;h.require=function(c){return k[c]};h.define=function(c,d){l("string"!==typeof c,1,'id must be a string "'+c+'"');l(k[c],2,'module already included "'+c+'"');l("function"!==typeof d,3,'function body for "'+c+'" must be an function "'+
d+'"');f[c]=!0;k[c]=d.call(h.prototype)};h.codename="new-age";h.version="1.0.0a-rc";window.hAzzle=h})(window);var hAzzle=window.hAzzle||(window.hAzzle={});
hAzzle.define("has",function(){var e=navigator.userAgent,k=window,f=k.document,l=f.createElement("div"),q=Object.prototype.toString,h={},c=function(){if(f.documentMode)return f.documentMode;for(var b=7,c;4<b;b--)if(c=f.createElement("div"),c.innerHTML="\x3c!--[if IE "+b+"]><span></span><![endif]--\x3e",c.getElementsByTagName("span").length)return b}(),d=function(b){return"function"===typeof h[b]?h[b]=h[b](k,f,l):h[b]},b=function(b,c,a,g){("undefined"===typeof h[b]||g)&&(h[b]=c);return a&&d(b)};b("multiArgs",
function(){var b=document.createElement("div");b.classList.add("a","b");return/(^| )a( |$)/.test(b.className)&&/(^| )b( |$)/.test(b.className)});b("mobile",/^Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(e));b("android",/^Android/i.test(e));b("opera","[object Opera]"===q.call(window.opera));b("firefox","undefined"!==typeof InstallTrigger);b("chrome",k.chrome);b("webkit","WebkitAppearance"in f.documentElement.style);b("safari",0<q.call(window.HTMLElement).indexOf("Constructor"));
b("ie",function(){return!!f.documentMode});b("classlist",!!document.documentElement.classList);return{has:d,add:b,load:function(b,c,a){b?c([b],a):a()},cache:h,clear:function(b){b.innerHTML="";return b},ie:c}});
hAzzle.define("Types",function(){var e,k=Object.prototype.toString,f=Array.isArray,l={},q="Arguments Array Boolean Date Error Function Map Number Object RegExp Set StringWeakMap ArrayBuffer Float32Array Float64Array Int8Array Int16Array Int32ArrayUint8Array Uint8ClampedArray Uint16Array Uint32Array".split(" "),h="ArrayBuffer Float32Array Float64Array Int8Array Int16Array Int32Array Uint8Array Uint8ClampedArray Uint16Array Uint32Array".split(" "),c=function(a){return"string"===typeof a},d=function(a){return"number"===
typeof a},b=function(a){return a&&a.window===a},m=function(a){return a?function(g){return k.call(g)==="[object "+a+"]"}:function(){}},n=function(a){var g=Object.prototype.toString.call(a);if("[object HTMLCollection]"===g||"[object NodeList]"===g)return!0;if(!("length"in a&&"item"in a))return!1;try{if(null===a(0)||a(0)&&a(0).tagName)return!0}catch(b){}return!1};this.isNodeList=n;for(e=q.length;e--;)l["[object "+q[e]+"]"]=!0;for(e=h.length;e--;)l["[object "+h[e]+"]"]=!1;return{isType:m,isArray:f,isEmpty:function(a){if(null==
a)return!0;if(f(a)||c(a)||m("Arguments")(a))return 0===a.length;for(var g in a)if(null!=a&&Object.prototype.hasOwnProperty.call(a,g))return!1;return!0},isWindow:b,isObject:function(a){return null!=a&&"object"===typeof a},isPlainObject:function(a){return"object"!==m(a)&&!b(a)&&Object.getPrototypeOf(a)==Object.prototype},isEmptyObject:function(a){for(var g in a)return!1;return!0},isNode:function(a){return!!a&&"object"===typeof a&&"nodeType"in a},isElement:function(a){return!(!a||1!==a.nodeType)},isString:c,
isArrayLike:function(a){return a&&"object"===typeof a&&"number"===typeof a.length&&l[k.call(a)]||!1},isNumber:d,isBoolean:function(a){return"boolean"===typeof a},isNaN:function(a){return d(a)&&a!=+a},isDefined:function(a){return"undefined"!==typeof a},isUndefined:function(a){return"undefined"===typeof a},isNodeList:n}});
hAzzle.define("Text",function(){var e=function(k){var f,l="",q=0;f=k.nodeType;if(!f)for(;f=k[q++];)l+=e(f);else if(1===f||9===f||11===f){if("string"===typeof k.textContent)return k.textContent;for(k=k.firstChild;k;k=k.nextSibling)l+=e(k)}else if(3===f||4===f)return k.nodeValue;return l};return{getText:e}});
hAzzle.define("Util",function(){var e=hAzzle.require("Types"),k=Object.keys,f=function(a,g){return Object.prototype.hasOwnProperty.call(a,g)},l=function(a,g,b,c){if(void 0===a)return a;hAzzle.err("function"!==typeof g,5,"'fn' must be a function in util.each()");var p,d=a.length,h;if("function"===typeof g&&"undefined"===typeof b&&"undefined"===typeof c&&e.isArray(a))for(;++p<d&&(p=c?a.length-p-1:p,!1!==g.call(a[p],a[p],p,a)););if(d===+d)for(p=0;p<d&&(p=c?a.length-p-1:p,!1!==g.call(a[p],a[p],p,a));p++);
else if(a)for(h in a)if(!1===g.call(a[h],a[h],h,a))break;return a},q=function(a,g,b){if("function"===typeof a){if(void 0===g)return a;b=b?b:3;return 1===b?function(b){return a.call(g,b)}:2===b?function(b,c){return a.call(g,b,c)}:3===b?function(b,c,r){return a.call(g,b,c,r)}:4===b?function(b,c,r,d){return a.call(g,b,c,r,d)}:function(){return a.apply(g,arguments)}}if(!a)return c},h=function(a,g,b){return a?"function"===typeof a?q(a,g,b):e.isObject(a)?d(a):m(a):c},c=function(a){return a},d=function(a){var g=
b(a),c=g.length;return function(a){if(!a)return!c;a=Object(a);for(var b=0,d,h;b<c;b++)if(d=g[b],h=d[0],d[1]!==a[h]||!(h in a))return!1;return!0}},b=function(a){for(var g=k(a),b=g.length,c=Array(b),d=0;d<b;d++)c[d]=[g[d],a[g[d]]];return c},m=function(a){return function(b){return b[a]}},n=function(a,b,c){if(null==a)return-1;var d=0,p=a.length;if(c)if("number"===typeof c)d=0>c?Math.max(0,p+c):c;else{c=h(void 0,void 0,1);for(var d=c(b),p=0,e=a.length;p<e;){var f=p+e>>>1;c(a[f])<d?p=f+1:e=f}d=p;return a[d]===
b?d:-1}for(;d<p;d++)if(a[d]===b)return d;return-1};return{map:function(a,b,c){if(a){b=h(b,c);c=a.length!==+a.length&&k(a);for(var d=(c||a).length,p=Array(d),e,f=0;f<d;f++)e=c?c[f]:f,p[f]=b.call(a[e],a[e],e,a);return p}return[]},some:function(a,b,c){if(a){b=h(b,c);c=(d||a).length;var d,e=0,f;for(a.length!==+a.length&&(d=d(a));e<c;e++)if(f=d?d[e]:e,b(a[f],f,a))return!0}return!1},reduce:function(a,b,c,d){a||(a=[]);b=q(b,d,4);var e=a.length!==+a.length&&k(a),h=(e||a).length,f=0,m;3>arguments.length&&
(hAzzle.err(!h,7," no collection length exist in collection.reduce()"),c=a[e?e[f++]:f++]);for(;f<h;f++)m=e?e[f]:f,c=b(c,a[m],m,a);return c},each:l,mixin:function(a){if(e.isObject(a))for(var b,c,d=1,h=arguments.length;d<h;d++)for(c in b=arguments[d],b)f(b,c)&&(a[c]=b[c]);return a},makeArray:function(a){if(e.isArray(a))return a;for(var b=-1,c=a.length,d=Array(c);++b<c;)d[b]=a[b];return d},merge:function(a,b){for(var c=+b.length,d=0,e=a.length;d<c;d++)a[e++]=b[d];a.length=e;return a},nodeName:function(a,
b){return a&&a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},unique:function(a,b,c,d){if(!a)return[];e.isBoolean(b)&&(d=c,c=b,b=!1);void 0!==c&&(c=h(c,d));d=[];for(var f=[],m=0,k,l=a.length;m<l;m++)if(k=a[m],b)m&&f===k||d.push(k),f=k;else if(c){var w=c(k,m,a);0>n(f,w)&&(f.push(w),d.push(k))}else 0>n(d,k)&&d.push(k);return d},indexOf:n,filter:function(a,b,c){var d=[];if(!a)return d;b=h(b,c);l(a,function(a,c,e){b(a,c,e)&&d.push(a)});return d},now:Date.now,has:f}});
hAzzle.define("Core",function(){var e=1,k=window.document,f=window.document,l="hAzzle_"+1*new Date,q,h,c=Array.prototype.indexOf,d={},b,m=k.createElement("div").compareDocumentPosition(k.createElement("div"))&1,n,a=function(){return!!n},g=function(a,b){a===b&&(n=!0);return 0},r=l.split("").sort(g).join("")===l,u=function(a,b){var c=b&&a,g=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||-2147483648)-(~a.sourceIndex||-2147483648);if(g)return g;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?
1:-1},p=function(a){return/^[^{]+\{\s*\[native \w/.test(""+a)},v=function(a){var b,c,g,f;q=a=a.ownerDocument||a;b=a.documentElement;if(9!==q.nodeType||!q.documentElement)return k;k=a;if(c=b.getAttribute("__hAzzle"))return h=d[c];b.setAttribute("__hAzzle",e);h={id:++e};h.qsa=p(a.querySelectorAll);h.compare=p(b.compareDocumentPosition);h.contains=p(b.contains);h.QSABugs=g=[];h.matchesBugs=f=[];h.qsa&&(c=a.createElement("div"),c.appendChild(a.createElement("select")),(a=a.createElement("option")).setAttribute("selected",
""),c.firstChild.appendChild(a),c.querySelectorAll(":checked").length||g.push(":checked"),h.QSABugs=g.length&&new RegExp(g.join("|")));p(b=b.webkitMatchesSelector||b.mozMatchesSelector||b.oMatchesSelector||b.msMatchesSelector)&&(h.matchesSelector=b,h.disconMatch=b.call(c,"div"),h.matchesBugs=f.length&&new RegExp(f.join("|")));d[e]=h;return d[e]};v(k);var s=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1},t=h.compare&&h.contains?function(a,b){var c=9===a.nodeType?
a.documentElement:a,g=b&&b.parentElement;return a===g||!!(g&&1===g.nodeType&&(c.contains?c.contains(g):a.compareDocumentPosition&&a.compareDocumentPosition(g)&16))}:function(a,b){if(b)for(;b=b.parentElement;)if(b===a)return!0;return!1},g=h.compare?function(a,g){if(a===g)return n=!0,0;var d=!a.compareDocumentPosition-!g.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===(g.ownerDocument||g)?a.compareDocumentPosition(g):1;return d&1||!m&&g.compareDocumentPosition(a)===d?a===q||a.ownerDocument===
f&&t(f,a)?-1:g===q||g.ownerDocument===f&&t(f,g)?1:b?c(b,a)-c(b,g):0:d&4?-1:1}:function(a,g){if(a===g)return n=!0,0;var d,e=0,h=a.parentNode,r=g.parentNode,m=[a],k=[g];if(!h||!r)return a===d?-1:g===d?1:h?-1:r?1:b?c(b,a)-c(b,g):0;if(h===r)return u(a,g);for(d=a;d=d.parentNode;)m.unshift(d);for(d=g;d=d.parentNode;)k.unshift(d);for(;m[e]===k[e];)e++;return e?u(m[e],k[e]):m[e]===f?-1:k[e]===f?1:0};return{environment:h,expando:l,addFeature:function(a,b){"string"===typeof a&&b&&(d[e][a]=b)},setDocument:v,
isXML:s,isHTML:!s(k),contains:t,unique:function(c){var d,e=[],f=0,h=0;n=!a;b=!r&&c.slice(0);c.sort(g);if(n){for(;d=c[h++];)d===c[h]&&(f=e.push(h));for(;f--;)c.splice(e[f],1)}b=null;return c},matches:h.matchesSelector,qsa:h.qsa,QSABugs:h.QSABugs,matchesBugs:h.matchesBugs}});
hAzzle.define("Collection",function(){var e=hAzzle.require("Util"),k=hAzzle.require("Types"),f=Array.prototype,l=f.concat,q=f.push,h=function(c,d,b){"undefined"===typeof d&&(d=0);"undefined"===typeof b&&(b=c?c.length:0);var e=-1;b=b-d||0;for(var f=Array(0>b?0:b);++e<b;)f[e]=c[d+e];return f};this.toJqueryZepto=function(){for(var c=this.length,d=this.elements;c--;)this[c]=d[c];return this};this.get=function(c){var d=this.elements;return void 0===c?h(d,0):0>c?d[this.length+c]:d[c]};this.eq=function(c){return hAzzle(-1===
c?h(this.elements,this.length-1):h(this.elements,c,c+1))};this.reduce=function(c,d,b){return e.reduce(this.elements,c,d,b)};this.indexOf=function(c,d,b){return null==d?-1:f.indexOf.call(d,c,b)};this.map=function(c,d){return hAzzle(e.map(this.elements,c,d))};this.each=function(c,d,b){e.each(this.elements,c,d,b);return this};this.slice=function(c,d){return hAzzle(h(this.elements,c,d))};this.concat=function(){var c=e.map(h(arguments),function(c){return c instanceof hAzzle?c.elements:c});return hAzzle(l.apply(this.elements,
c))};this.is=function(c){return 0<this.length&&0<this.filter(c).length};this.not=function(c){return this.filter(c,!0)};this.index=function(c){var d=this.elements;return c?"string"===typeof c?e.indexOf(hAzzle(c).elements,d[0]):e.indexOf(d,c instanceof hAzzle?c.elements[0]:c):d[0]&&d[0].parentElement?this.first().prevAll().length:-1};this.add=function(c,d){var b=c;"string"===typeof c&&(b=hAzzle(c,d).elements);return this.concat(b)};this.first=function(c){return c?this.slice(0,c):this.eq(0)};this.last=
function(c){return c?this.slice(this.length-c):this.eq(-1)};this.even=function(){return this.filter(function(c){return 0!==c%2})};this.odd=function(){return this.filter(function(c){return 0===c%2})};e.each({next:"nextElementSibling",prev:"previousElementSibling"},function(c,d){this[d]=function(b){return this.map(function(b){return b[c]}).filter(b)}}.bind(this));e.each({prevAll:"previousElementSibling",nextAll:"nextElementSibling"},function(c,d){this[d]=function(){var b=[];this.each(function(d){for(;(d=
d[c])&&9!==d.nodeType;)b.push(d)});return hAzzle(b)}}.bind(this));return{makeArray:function(c,d){var b=d||[];void 0!==c&&(k.isArrayLike(Object(c))?e.merge(b,k.isString(c)?[c]:c):q.call(b,c));return b},inArray:function(c,d,b){return void 0===d?-1:f.indexOf.call(d,c,b)},slice:h}});
hAzzle.define("Jiesa",function(){var e=hAzzle.require("Util"),k=hAzzle.require("Core"),f=hAzzle.require("Collection"),l=hAzzle.require("Types"),q=hAzzle.require("has"),h=hAzzle.require("selector"),c=/^(?:#([\w-]+)|\.([\w-]+)|(\w+))$/,d=/^(\w+)(?:#([\w-]+)|)(?:\.([\w-]+)|)$/,b=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g,m=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,n=/^(\w*)(?:#([\w\-]+))?(?:\[([\w\-\=]+)\])?(?:\.([\w\-]+))?$/,a=/^\s*[+~]/,g=/[\n\t\r]/g,r={":enabled":function(a){return!1===
a.disabled},":disabled":function(a){return!0===a.disabled},":checked":function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},":hidden":function(a){var b=a.style;return!b||"none"!==b.display&&"hidden"!==b.visibility?"hidden"===a.type:!0},":visible":function(a){return!r[":hidden"](a)}},u=function(c,g,d){var e=c,f=c.getAttribute("id"),h=f||"__hAzzle__",r=c.parentNode,k=a.test(g);if(k&&!r)return[];f?h=h.replace(/'/g,"\\$&"):c.setAttribute("id",h);k&&r&&
(c=c.parentNode);g=g.match(b);for(r=0;r<g.length;r++)g[r]="[id='"+h+"'] "+g[r];g=g.join(",");try{return d.call(c,g)}finally{f||e.removeAttribute("id")}},p=function(a,b,c){return c&&9!==c.nodeType?u(c,b,function(b){return a.matches(b)}):a.matches(b)},v=function(a){return a?"string"===typeof a?s(a):!a.nodeType&&l.isArrayLike(a)?a[0]:a:document},s=function(a,b){var r,m,n,l,p=[];b=v(b);if(!a||"string"!==typeof a)return p;if(1!==(m=b.nodeType)&&9!==m&&11!==m)return[];if(k.isHTML){if(r=c.exec(a)){if(a=
r[1]){if(9===m)return(n=b.getElementById(a))&&n.id===a?[n]:[];if(b.ownerDocument&&(n=b.ownerDocument.getElementById(a))&&k.contains(b,n)&&n.id===r)return[n]}else if(a=r[2])l=b.getElementsByClassName(a);else if(a=r[3])l=b.getElementsByTagName(a);return f.slice(l)}if(r=d.exec(a)){m=b.getElementsByTagName(r[1]);var s=r[2],t=r[3];e.each(m,function(a){var b;(b=a.id===s)||(b=q.has("classList")?a.classList.contains(t):0<=(" "+a.className+" ").replace(g," ").indexOf(t));b&&p.push(a)});return p}if(hAzzle.installed.selector&&
k.qsa&&(!k.QSABugs||!k.QSABugs.test(a)))try{return l=1===b.nodeType?u(b,a,b.querySelectorAll):b.querySelectorAll(a)}catch(y){}}hAzzle.err(!hAzzle.installed.selector,22," the selector.js module need to be installed");return h.find(a,b)},t=function(a,b,c){if(b.nodeType)return a===b;(a.ownerDocument||a)!==document&&k.setDocument(a);b="string"===typeof b?b.replace(m,"='$1']"):b;if(b instanceof hAzzle)return e.some(b.elements,function(b){return t(a,b)});if(a===document)return!1;var g=n.exec(b);if(g)return g[1]&&
(g[1]=g[1].toLowerCase()),g[3]&&(g[3]=g[3].split("=")),g[4]&&(g[4]=" "+g[4]+" "),(!g[1]||a.nodeName.toLowerCase()===g[1])&&(!g[2]||a.id===g[2])&&(!g[3]||(g[3][1]?a.getAttribute(g[3][0])===g[3][1]:a.hasAttribute(g[3][0])))&&(!g[4]||0<=(" "+a.className+" ").indexOf(g[4]));if(g=r[b])return!!g(a);if(!k.matches||!k.isHTML||k.rbuggyMatches&&k.rbuggyMatches.test(b)||k.QSABugs&&k.QSABugs.test(b))return hAzzle.err(!hAzzle.installed.selector,22," the selector.js module need to be installed"),h.matches(b,a,
b);try{var d=p(a,b,c);if(d||k.disconMatch||a.document&&11!==a.document.nodeType)return d}catch(f){}};this.find=function(a,b,c){if(!c){if("string"!==typeof a){var g=0,d=this.length,r=this.elements;return hAzzle(e.filter(hAzzle(a).elements,function(a){for(;g<d;g++)if(k.contains(r[g],a))return!0}))}return e.reduce(this.elements,function(b,c){return hAzzle(b.concat(f.slice(s(a,c))))},[])}return s(a,b)};this.filter=function(a,b){if(void 0===a)return this;if("function"===typeof a){var c=[];this.each(function(b,
g){a.call(b,g)&&c.push(b)});return hAzzle(c)}return this.filter(function(){return t(this,a)!==(b||!1)})};return{matchesSelector:p,matches:t,pseudos:r,find:s}});
hAzzle.define("Strings",function(){var e=String.prototype.trim,k=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,f=/[A-Z]/g,l=/^-ms-/,q=/-([\da-z])/gi,h=[],c=function(b,c){return c.toUpperCase()},d=function(b){return"-"+b.charAt(0).toLowerCase()};return{capitalize:function(b){return b&&"string"===typeof b?b.charAt(0).toUpperCase()+b.slice(1):""},unCapitalize:function(b){return b&&"string"===typeof b?b.charAt(0).toLowerCase()+b.slice(1):""},hyphenate:function(b){return"string"===typeof b?b?b.replace(f,d):b:(b=
"number"===typeof b?""+b:"")?"data-"+b.toLowerCase():b},camelize:function(b){return b&&"string"===typeof b?h[b]?h[b]:h[b]=b.replace(l,"ms-").replace(q,c):"number"===typeof b||"boolean"===typeof b?""+b:b},trim:function(b){return null==b?"":e?"string"===typeof b?b.trim():b:(b+"").replace(k,"")}}});
hAzzle.define("Storage",function(){function e(){this.expando=h.expando+Math.random()}function k(a,b,e){if(void 0===e&&1===a.nodeType)if(e="data-"+b.replace(d,"-$1").toLowerCase(),e=a.getAttribute(e),"string"===typeof e){try{e="true"===e?!0:"false"===e?!1:"null"===e?null:+e+""===e?+e:c.test(e)?JSON.parse(e+""):e}catch(f){}n.set(a,b,e)}else e=void 0;return e}var f=hAzzle.require("Util"),l=hAzzle.require("Strings"),q=hAzzle.require("Types"),h=hAzzle.require("Core"),c=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,
d=/([A-Z])/g,b=/\S+/g;e.accepts=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};e.prototype={register:function(a,b){var c={};c[this.expando]={value:b||{},writable:!0,configurable:!0};a.nodeType?a[this.expando]={value:b||{}}:Object.defineProperties(a,c);return a[this.expando]},cache:function(a,b){if(!e.accepts(a))return{};var c=a[this.expando];return c?c:this.register(a,b)},set:function(a,b,c){if(a){var d;a=this.cache(a);if("string"===typeof b)a[b]=c;else if(q.isEmptyObject(a))f.mixin(a,
b);else for(d in b)a[d]=b[d];return a}},access:function(a,b,c){if(void 0===b||b&&"string"===typeof b&&void 0===c)return c=this.get(a,b),void 0!==c?c:this.get(a,l.camelize(b));this.set(a,b,c);return void 0!==c?c:b},get:function(a,b){var c=this.cache(a);return void 0!==c&&void 0===b?c:c[b]},release:function(a,c){var d,e,f=this.cache(a);if(void 0===c)this.register(a);else for(q.isArray(c)?e=c.concat(c.map(l.camelize)):(d=l.camelize(c),c in f?e=[c,d]:(e=d,e=f[e]?[e]:e.match(b)||[])),d=e.length;d--;)delete f[e[d]]},
hasData:function(a){return!q.isEmptyObject(a[this.expando]||{})},flush:function(a){a[this.expando]&&delete a[this.expando]}};var m=new e,n=new e;this.data=function(a,b){var c,d,e,f=this.elements[0],h=f&&f.attributes;if(void 0===a){if(this.length&&(e=n.get(f),1===f.nodeType&&!m.get(f,"hasDataAttrs"))){for(c=h.length;c--;)h[c]&&(d=h[c].name,0===d.indexOf("data-")&&(d=l.camelize(d.slice(5)),k(f,d,e[d])));m.set(f,"hasDataAttrs",!0)}return e}if("object"===typeof a)return this.each(function(b){n.set(b,
a)});var q=l.camelize(a);if(f&&void 0===b){e=n.get(f,a);if(void 0!==e)return e;e=n.get(f,q);var w=m.get(this,"hasDataAttrs"),x=-1!==a.indexOf("-");if(void 0!==e)return e;e=k(f,q,void 0);if(void 0!==e)return e}else this.each(function(c){var d=n.get(c,q);n.set(c,q,b);x&&void 0!==d&&n.set(c,a,b);x&&void 0===w&&n.set(c,a,b)})};this.removeData=function(a){return this.each(function(b){n.release(b,a)})};return{"private":m,data:n}});
hAzzle.define("curCSS",function(){var e=hAzzle.require("Storage"),k=hAzzle.require("Core"),f=hAzzle.require("has"),l=/^(width|height)$/,q=/^(b|big|i|small|tt|abbr|acronym|cite|code|dfn|em|kbd|strong|samp|var|a|bdo|br|img|map|object|q|script|span|sub|sup|button|input|label|select|textarea)$/i,h=/^(li)$/i,c=/^(tr)$/i,d=/^(_table)$/i,b=function(a){if(a)return void 0===e["private"].get(a,"computed")&&e["private"].access(a,"computed",{computedStyle:null}),e["private"].get(a,"computed")},m=function(a){var c;
if(null===b(a).computedStyle){c=b(a);if(a&&null!==a.ownerDocument){var d=!1;a?(void 0!==a.ownerDocument&&(d=a.ownerDocument.defaultView),a=d&&d.opener?d.getComputedStyle(a,null):window.getComputedStyle(a,null)):a=a.style}else a="";c=c.computedStyle=a}else c=b(a).computedStyle;return c},n=function(a){return parseFloat(a)||0},a=function(b,e,u){b=b instanceof hAzzle?b.elements[0]:b;var p=0;if(l.test(e)&&0===a(b,"display")){b.style.display="none";var v=b.style,s;s=b&&b.tagName.toString().toLowerCase();
s=q.test(s)?"inline":h.test(s)?"list-item":c.test(s)?"table-row":d.test(s)?"table":"block";v.display=s}if(f.has("ie")&&"auto"===e){if("height"===e)return b.offsetHeight;if("width"===e)return b.offsetWidth}if(!u){if("height"===e&&"border-box"!==a(b,"boxSizing").toString().toLowerCase())return b.offsetHeight-n(a(b,"borderTopWidth"))-n(a(b,"borderBottomWidth"))-n(a(b,"paddingTop"))-n(a(b,"paddingBottom"));if("width"===e&&"border-box"!==a(b,"boxSizing").toString().toLowerCase())return b.offsetWidth-n(a(b,
"borderLeftWidth"))-n(a(b,"borderRightWidth"))-n(a(b,"paddingLeft"))-n(a(b,"paddingRight"))}if(u=m(b))(f.ie||f.has("firefox"))&&"borderColor"===e&&(e="borderTopColor"),p=9===f.ie&&"filter"===e?u.getPropertyValue(e):u[e],""!==p||k.contains(b.ownerDocument,b)||(p=b.style[e]);return void 0!==p?p+"":p};return{computed:b,styles:m,css:a}});
hAzzle.define("Setters",function(){var e=hAzzle.require("Util"),k=hAzzle.require("Core"),f=hAzzle.require("Types"),l=/\S+/g,q=/\r/g,h="multiple selected checked disabled readonly required async autofocus compact nowrap declare noshade hreflang onload srcnoresize defaultChecked autoplay controls defer autocomplete hidden tabindex readonly type accesskey dropzone spellcheck ismap loop scoped open".split(" "),c={},d={},b={"class":"className","for":"htmlFor"},m={get:{},set:{}},n={get:{},set:{}},a={get:{},
set:{}},g={get:{},set:{}},r={get:{},set:{}},u=function(a){return a instanceof hAzzle?a.elements:a},p=function(a,b){var e=c[b.toLowerCase()];return e&&d[a.nodeName]&&e},v=function(a,c){a=u(a);var d,e,g=0,f=c&&c.match(l);if(f&&1===a.nodeType)for(;d=f[g++];)e=b[d]||d,p(a,d)?a[e]=!1:a.removeAttribute(d),a.removeAttribute(d)},s=function(a,b,c){var d=(a=u(a))?a.nodeType:void 0,e,f;if(d&&(3!==d||8!==d||2!==d)){if("undefined"===typeof a.getAttribute)return t(a,b,c);if(d=1!==d||!k.isXML(a))b=b.toLowerCase(),
e=n["undefined"===c?"get":"set"][b]||p(a,b)?r["undefined"===c?"get":"set"][b]:g["undefined"===c?"get":"set"][b];if(void 0===c){if(e&&(f=e.get(a,b))&&null!==f)return f;f=a.getAttribute(b,2);return null==f?void 0:f}if(c){if(e&&void 0!==(f=e.set(a,c,b)))return f;a.setAttribute(b,c+"")}else v(a,b)}return""},t=function(a,c,d){var e=(a=u(a))?a.nodeType:void 0,f,g;if(e&&(3!==e||8!==e||2!==e)){if(1!==e||k.isHTML)c=b[c]||c,f="undefined"===d?m.get[c]:m.set[c];return"undefined"!==typeof d?f&&void 0!==(g=f.set(a,
d,c))?g:a[c]=d:f&&null!==(g=f(a,c))?g:a[c]}return""};this.val=function(b){var c,d,g;d=this.elements[0];if(arguments.length)return g=f.isType("Function")(b),this.each(function(d,h){var k;1===d.nodeType&&(k=g?b.call(d,h,hAzzle(d).val()):b,null==k?k="":"number"===typeof k?k+="":f.isArray(k)&&(k=e.map(k,function(a){return null==a?"":a+""})),c=a.set[d.type]||a.set[d.nodeName.toLowerCase()],c&&void 0!==c(d,k,"value")||(d.value=k))});if(d&&d!==window){if(c=a.get[d.type]||a.get[d.nodeName.toLowerCase()])return c(d,
"value");d=d.value;return"string"===typeof d?d.replace(q,""):null==d?"":d}};this.prop=function(a,b){var c=this.elements;if("object"===typeof a)return this.each(function(b){e.each(a,function(a,c){t(b,c,a)})});if("undefined"===typeof b)return t(c[0],a);this.each(c,function(c){t(c,a,b)})};this.toggleProp=function(a){return this.each(function(b){return b.prop(a,!b.prop(a))})};this.removeProp=function(a){return this.each(function(){delete this[b[a]||a]})};this.removeAttr=function(a){return this.each(function(b){v(b,
a)})};this.attr=function(a,b){var c=this.elements;return"object"===typeof a?this.each(function(b){e.each(a,function(a,c){s(b,c,a)})}):"undefined"===typeof b?s(c[0],a):this.each(function(c){s(c,a,b)})};e.each(h,function(a){c[h[a]]=h[a]});e.each("input select option textarea button form details".split(" "),function(a){d[a.toUpperCase()]=!0});e.each("cellPadding cellSpacing maxLength rowSpan colSpan useMap frameBorder contentEditable textContent valueType tabIndex readOnly type accessKey tabIndex dropZone spellCheck hrefLang isMap srcDoc mediaGroup autoComplete noValidate radioGroup".split(" "),
function(a){b[a.toLowerCase()]=a});return{attrHooks:n,propHooks:m,valHooks:a,boolHooks:r,nodeHooks:g,propMap:b,boolAttr:c,boolElem:d,removeAttr:v,attr:s,prop:t}});
hAzzle.define("attrHooks",function(){var e=hAzzle.require("Util"),k=hAzzle.require("Setters"),f=function(){var e=document.createElement("input");e.type="checkbox";e=document.createElement("input");e.value="t";e.type="radio";return"t"===e.value}();e.mixin(k.attrHooks.set,{type:function(k,q){if(!f&&"radio"===q&&e.nodeName(k,"input")){var h=k.value;k.setAttribute("type",q);h&&(k.value=h);return q}}});return{}});
hAzzle.define("propHooks",function(){var e=hAzzle.require("Util"),k=hAzzle.require("Setters");e.mixin(k.propHooks.get,{tabIndex:function(e){return e.hasAttribute("tabindex")||/^(?:input|select|textarea|button)$/i.test(e.nodeName)||e.href?e.tabIndex:-1}});document.createElement("select").appendChild(document.createElement("option")).selected||(k.propHooks.get.selected=function(e){(e=e.parentNode)&&e.parentNode&&e.parentNode.selectedIndex;return null});return{}});
hAzzle.define("valHooks",function(){var e=hAzzle.require("Util"),k=hAzzle.require("Strings"),f=hAzzle.require("Text"),l=hAzzle.require("Types"),q=hAzzle.require("Collection"),h=hAzzle.require("Setters"),c=function(){var b=document.createElement("input");b.type="checkbox";b.checked=!0;b=b.getAttributeNode("checked");return!b||!b.specified}(),d=function(b,c,d){var a=b.length;for(d=0>d?Math.max(0,a+d):d||0;d<a;d++)if(b[d]===c)return d;return-1};e.mixin(h.valHooks.set,{select:function(b,c){for(var e,
a,g=b.options,f=q.makeArray(c),h=g.length;h--;)if(a=g[h],a.selected=0<=d(f,a.value))e=!0;e||(b.selectedIndex=-1);return f}});e.mixin(h.valHooks.get,{option:function(b){var c=b.getAttribute(name,2);return null!==c?c:k.trim(f.getText(b))},select:function(b){var c=b.selectedIndex,d="select-one"===b.type;b=b.options;var a=[],e,f,h;if(0>c)return"";h=d?c:0;for(f=d?c+1:b.length;h<f;h++)if(e=b[h],e.selected&&null===e.getAttribute("disabled")&&(!e.parentElement.disabled||"OPTGROUP"!==e.parentElement.tagName)){e=
hAzzle(e).val();if(d)return e;a.push(e)}return d&&!a.length&&b.length?b[c].value:a}});e.each(["radio","checkbox"],function(b){h.valHooks.set[b]=function(b,c){if(l.isArray(c))return b.checked=0<=d(c,hAzzle(b).val())}});c||(h.valHooks.get[val]=function(b){return null===b.getAttribute("value")?"on":b.value});return{}});
(function(e){function k(b){return"string"===typeof b?e.document.createTextNode(b):b}function f(b){var c=e.document.createDocumentFragment(),a=q.call(b,0),d=0,f=b.length;if(1===b.length)return k(b[0]);for(;d<f;d++)try{c.appendChild(k(a[d]))}catch(h){}return c}for(var l=Array.prototype,q=l.slice,h=l.indexOf,l=(e.Element||e.Node||e.HTMLElement).prototype,c=["append",function(){this.appendChild(f(arguments))},"prepend",function(){this.firstChild?this.insertBefore(f(arguments),this.firstChild):this.appendChild(f(arguments))},
"before",function(){var b=this.parentElement;b&&b.insertBefore(f(arguments),this)},"after",function(){this.parentElement&&(this.nextSibling?this.parentElement.insertBefore(f(arguments),this.nextSibling):this.parentElement.appendChild(f(arguments)))},"replace",function(){this.parentElement&&this.parentElement.replaceChild(f(arguments),this)},"remove",function(){this.parentElement&&this.parentElement.removeChild(this)},"matches",l.matchesSelector||l.webkitMatchesSelector||l.mozMatchesSelector||l.msMatchesSelector||
function(b){var c=this.parentElement;return!!c&&-1<h.call(c.querySelectorAll(b),this)}],d=c.length;d;d-=2)l[c[d-2]]||(l[c[d-2]]=c[d-1]);try{new e.CustomEvent("?")}catch(b){e.CustomEvent=function(b,c){function a(a,b,c,d){this.initEvent(a,b,c);this.detail=d}return function(d,e){var f=document.createEvent(b);if("string"!==typeof d)throw Error("An event name must be provided");"Event"===b&&(f.initCustomEvent=a);null==e&&(e=c);f.initCustomEvent(d,e.bubbles,e.cancelable,e.detail);return f}}(e.CustomEvent?
"CustomEvent":"Event",{bubbles:!1,cancelable:!1,detail:null})}})(window);